server:
  port: 8000
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://192.168.44.128:3306/rain_order?useUnicode=true&characterEncoding=utf-8&useSSl=false
#    username: root
#    password: 123456
#
#mybatis:
#  type-aliases-package: com.rain.cloud.entity.order.dto
#  mapper-locations: classpath*:sqlmapper/*.xml
