server:
  port: 8010
spring:
  application:
    name: rain-product-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:
    username:
    password:

mybatis:
  type-aliases-package: com.haimin.cloud.dto
  mapper-locations: classpath*:sqlmapper/*Mapper.xml