package com.rain.cloud.product.dao;

import com.rain.cloud.common.entity.product.dto.ProductDto;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IProductInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int insert(ProductDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int insertSelective(ProductDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    ProductDto selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductDto record);
}